version: "3.8"

services:
  nginx:
    build: ./_nginx
    ports:
      - 80:80
    depends_on:
#      - auth_service
      - lookup_service
#      - seller_service

  # auth_service:
  #   build: ./AuthService/
  #   command: gunicorn AuthService.wsgi:application --bind 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   working_dir: /AuthService/
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./.local.env

  lookup_service:
    build: ./LookupService/
    command: gunicorn LookupService.wsgi:application --bind 0.0.0.0:8001
    ports:
      - 8001:8001
    working_dir: /LookupService/ # 반드시 / 여야함
    expose:
      - 8001
    env_file:
      - ./LookupService/.local.env

  # seller_service:
  #   build: ./SellerService/
  #   command: gunicorn SellerService.wsgi:application --bind 0.0.0.0:8002
  #   ports:
  #     - 8002:8002
  #   working_dir: /SellerService/
  #   expose:
  #     - 8002
  #   env_file:
  #     - ./.local.env

  ##
  # @TODO
  # PaymentService - PORT : 8003
  ## 